### ISSUE TITLE
Inno Setup hardcoded?

### ISSUE THREAD

**Issue by aadler** [r-windows/r-base#13]
Not everyone installs Inno to Program Files this is why there is the `ISDIR` variable in MkRules.dist. However, the path is hardcoded in `PKGBUILD` in line 49: `INNOSETUP="C:/Program Files (x86)/Inno Setup 6/ISCC.exe"`.

**Comment by aadler** [comment]
More frustrating. Figured out how to pass BLAS patch, how to shut-off 32 bit build, and now I get this error:
```
cp -pRf ../../../Tcl R-devel
rm -f R-devel/Tcl*/lib/*.lib
------------ not including 32-bit files
for f in ; do \
  cp "$f" R-devel/bin/i386; \
done
for f in ; do \
  cp "$f" R-devel/bin/x64; \
done
adding MD5 checksums
../../../bin/x64/Rscript JRins.R \
  R-devel R-devel 0 \
  1 R-core "C:/R/Inno"
"C:/R/Inno/iscc" R.iss > R-devel.log 2>&1
make[2]: *** [Makefile:175: R-devel-win.exe] Error 2
make[1]: *** [Makefile:402: rinstaller] Error 2
make: *** [Makefile:416: distribution] Error 2
==> ERROR: A failure occurred in build().

```

I guess I'll uninstall Inno and reinstall it in default location, but that is frustrating.

**Comment by jeroen** [comment]
So what is in the generated `R-devel.log  ? Maybe you forgot some latex packages?

**Comment by aadler** [comment]
It's 21,179 lines long. Shall I post it?

**Comment by jeroen** [comment]
Just look for error messages.

**Comment by aadler** [comment]
Outside of
```
"C:/R/Inno/iscc" R.iss > R-devel.log 2>&1
make[2]: *** [Makefile:175: R-devel-win.exe] Error 2
make[1]: *** [Makefile:402: rinstaller] Error 2
make: *** [Makefile:416: distribution] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

The others don'te seem like real errors:
```
Overfull \hbox (50.80455pt too wide) in paragraph at lines 8992--8992
 []@texttt Fortran runtime error: Index '1' of dimension 1 of array 'x' above u
pper bound of 0[] 
```

```
mat.c: In function 'chol_up':
mat.c:1877:7: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
       if (*n>1) R[1] = -2.0;return; /* signals error */
       ^~
mat.c:1877:29: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
       if (*n>1) R[1] = -2.0;return; /* signals error */
```
```
[53]
Overfull \hbox (55.2397pt too wide) in paragraph at lines 4726--4726
 []@texttt java.lang.UnsupportedClassVersionError: ... Unsupported major.minor 
version 52.0[] 
```

**Comment by aadler** [comment]
Makefile 175 in rinstaller is
```bash
$(RPREFIX)-win.exe: R.iss
	"$(ISDIR)/iscc" R.iss > $(RPREFIX).log 2>&1
```

**Comment by aadler** [comment]
Does it matter that in my install iscc is actually uppercase ISCC.exe?
<img width="833" alt="iscc" src="https://user-images.githubusercontent.com/5596401/80424054-f7205600-88ae-11ea-8fad-26ac0a489a94.png">

**Comment by aadler** [comment]
That isn't the issue. Build failed at same place again. 
[r-devel.log](https://github.com/r-windows/r-base/files/4542354/r-devel.log)

**Comment by jeroen** [comment]
I mean the `R-devel.log` that innosetup is generating with this line:

```
"C:/R/Inno/iscc" R.iss > R-devel.log 2>&1
```

It is probably in `src/gnuwin32/installer/R-devel.log`. I think the error message will be in there.

**Comment by aadler** [comment]
Correct as usual, @jeroen . Do you know what this error means?
```bash
Error on line 5482 in C:\R\R40\src\R-source\src\gnuwin32\installer\R.iss: Directive or parameter "Components" expression error: Parameter "Components" includes an unknown component.
Compile aborted.
```

[R-devel.log](https://github.com/r-windows/r-base/files/4546854/R-devel.log)

**Comment by aadler** [comment]
The the offending lines are posed below. Is it because I stopped the i386 build and just built x64? I did that by commenting out the section for 32-bit build in `PKGBUILD` and changing the `sed` call to remove `@home32@` since the Makefiles for rinstaller will try and compress that (non-existent) directory, so now line 95 looks like:
```
sed -e "s|@win@|64|" -e "s|@texindex@|${TEXINDEX}|" -e "s|@home32@||" "${srcdir}/MkRules.local.in" > MkRules.local
```

Lines 5482-5483 of R.iss are:
```
Source: "R-devel\Tcl\bin\tcl86.dll"; DestDir: "{app}\Tcl\bin"; Flags: ignoreversion; Components: i386
Source: "R-devel\Tcl\bin\tk86.dll"; DestDir: "{app}\Tcl\bin"; Flags: ignoreversion; Components: i386
```
It is necessary for my build right now to just build 64 bit, as otherwise I don't know of any other way to use OpenBLAS for windows.

**Comment by jeroen** [comment]
I don't understand what you're trying to do, and why.

You can install openblas in rtools40 like this:

```sh
pacman -S mingw-w64-{i686,x86_64}-openblas
```

This installs both the 32-bit and 64-bit oepnblas. Perhaps you can use those to build your custom Rblas, if that is what you are after, but we don't support this officially, it may not work.

If you want to customize your installer to work with your hacked version of R, I can't help with that. This is really not the purpose of this repository.

**Comment by aadler** [comment]
Part of the purpose of OpenBLAS, similar to ATLAS, is to build it to take full advantage of the local machine. What I am trying to do is what I've been doing for nearly the past decade, which is to use a custom OpenBLAS. This has worked for all of R3, pretty much. Something about this build system is making R.iss hiccup. I'm trying to figure out what it is so that Windows users can still use OpenBLAS. 

If you really have no idea wht R.iss lines 5482-5483 are complaining, I have one more thing I can try, which is to build a new diff that changes Mkrules.dist AFTER the 32 bit build before the 64 bit build.

**Comment by aadler** [comment]
@jeroen If I wanted to use `pacman -S mingw-w64-{i686,x86_64}-openblas` How would I pass `ATLAS_PATH` so that the proper 32/64 bit versions are used in each phase of the build given that the libs are installed to `C:\rtools40\mingw32\lib` and `C:\rtools40\mingw64\lib` respectively.

**Comment by aadler** [comment]
OK. I managed by using the pacman OpenBLAS and setting `ATLAS_PATH="/mingw$(WIN)/lib/"` in `MkRules.local.in`. This issue has gotten way off target anyway, as the original issue was the hardcoding of INNOSETUP in PKGBUILD. I'll close this and open an issue which is more focused. Thank you for your patience.

**Comment by jeroen** [comment]
Actually I don't think you need to set any ATLAS_PATH because the linker will automatically find all libs that you installed with pacman.

**Comment by aadler** [comment]
I tried that first. It didn't work since I had passed `USE_ATLAS = YES` so src/extras/blas/Makevars.win was looking for ATLAS_PATH since it looks like this (after my patch):
```bash
#-*- Makefile -*-
include ../../gnuwin32/MkRules

all: ../../../$(BINDIR)/Rblas.dll

## suppress lots of warnings: this is a dummy
blas00.o: blas00.c
	$(CC) -O3 -I../../include  -c $< -o $@

## Rblas.dll imports xerbla_ from R.dll
ifeq "$(USE_ATLAS)" "YES"
../../../$(BINDIR)/Rblas.dll: blas00.o ../../gnuwin32/dllversion.o
	@$(ECHO) -------- Building $@ --------
	$(DLL) -shared $(DLLFLAGS) -o $@ $^ Rblas.def \
	   -L../../../$(IMPDIR) -lR  -L"$(ATLAS_PATH)" -lopenblas
else
../../../$(BINDIR)/Rblas.dll: blas.o cmplxblas.o ../../gnuwin32/dllversion.o
	@$(ECHO) -------- Building $@ --------
	$(DLL) -shared $(DLLFLAGS) -o $@ $^ Rblas.def -L../../../$(IMPDIR) -lR $(FLIBS)
endif
```

I'm thinking maybe if I change the original from 
```
ifeq "$(USE_ATLAS)" "YES"
../../../$(BINDIR)/Rblas.dll: blas00.o ../../gnuwin32/dllversion.o
	@$(ECHO) -------- Building $@ --------
	$(DLL) -shared $(DLLFLAGS) -o $@ $^ Rblas.def \
	   -L../../../$(IMPDIR) -lR  -L"$(ATLAS_PATH)" -lf77blas -latlas
```

to
```
ifeq "$(USE_ATLAS)" "YES"
../../../$(BINDIR)/Rblas.dll: blas00.o ../../gnuwin32/dllversion.o
	@$(ECHO) -------- Building $@ --------
	$(DLL) -shared $(DLLFLAGS) -o $@ $^ Rblas.def \
	   -L../../../$(IMPDIR) -lR  -lopenblas
```

removing the link to `ATLAS_PATH` may work. But passing `$(WIN)`-sensitive `ATLAS_PATH` compiled and passed the built-in checks. I can't install it right this minute; I need to wait a week or three until the semester ends. Thanks!
