### ISSUE TITLE
full-build.sh needs to set the variable $srcdir

### ISSUE THREAD

**Issue by AndreMikulec** [r-windows/r-base#17]
full-build.sh does *not* set the variable $srcdir

quick-build.sh does set the variable $srcdir
```
# get absolute paths
srcdir=$(dirname $(realpath $0))
```

The variable $srcdir is *used* in PKGBUILD (that is called from both quick-build.sh and full-build.sh).

**Comment by jeroen** [comment]
The `srcdir` variable is automatically set when running `makepkg-mingw` and always refers to the directory that contains the `PKGBUILD`. You will see that `srcdir` is used in all `PKGBUILD` files: https://github.com/r-windows/rtools-packages

**Comment by AndreMikulec** [comment]
O.K.
I understand.  Thanks.
https://www.archlinux.org/pacman/PKGBUILD.5.html
