### ISSUE TITLE
Build r-base check logs location?

### ISSUE THREAD

**Issue by AndreMikulec** [r-windows/r-base#29]
Jeroen Ooms,

(1)
Where are the r-base check logs location?

At one time, they were here:

```
https://ftp.opencpu.org/current/check.log
https://ftp.opencpu.org/archive/r-patched/svn_number/check.log
https://ftp.opencpu.org/archive/r-release/R-x.y.z/check.log
```
Perhaps, they moved, or are no longer being displayed on the web?

(2)
The case seem that the 	%rversion% variable is not available 
when the archive 'r-version' directory is created (in appveyor.yml):
```
https://ftp.opencpu.org/archive/
%rversion%/	2021-11-01 19:31	-
```
In the file https://github.com/r-windows/r-base/blob/master/appveyor.yml
and in the "deploy:" section
maybe, instead of 
```
archive: "%rversion%"
```
you meant to say?
```
rversion: "%rversion%"
```

**Comment by jeroen** [comment]
The check logs for the daily windows r-patched and r-devel builds are only published on appveyor: https://ci.appveyor.com/project/jeroen/r-base/history

Check logs for all commits are available on https://r-devel.github.io/
