### ISSUE TITLE
MikTeX installation path

### ISSUE THREAD

**Issue by yutannihilation** [r-windows/r-base#33]
In my machine it's installed in

```
/c/Users/<user name>/AppData/Local/Programs/MiKTeX/miktex/
```

This is because I chose to install "a private installation," which is recommended by the official guide.

https://miktex.org/howto/install-miktex

**Comment by jeroen** [comment]
Isn't that the same as what we have in https://github.com/r-windows/r-base/blob/master/PKGBUILD#L61 ?

**Comment by yutannihilation** [comment]
Ah, yes. I was looking at this line. Should this match to it? Or this doesn't matter?

https://github.com/r-windows/r-base/blob/8118a780818df1f870ccaebc36d897471bd76415/quick-build.sh#L9

**Comment by jeroen** [comment]
No that is another; you need the one that starts with `$HOME/AppData/.....`

**Comment by yutannihilation** [comment]
Thanks for confirming, here's a pull request to fix it.

https://github.com/r-windows/r-base/pull/35
